import Header from '@/components/SolicitudesServicios/shared/Header';
import { useForm } from 'react-hook-form';
import Swal from 'sweetalert2';
import { ApiService } from '@/services/api.service';
import { Fragment, useEffect, useState } from 'react';
import { v4 as uuidV4 } from 'uuid';
import SolicitudesServicioList from '@/components/SolicitudesServicios/viajarAhora/SolicitudesServicioList';
import CrearSolicitudServicio, {
  SolicitudServicioInfo,
} from '@/components/SolicitudesServicios/viajarAhora/CrearSolicitudServicio';
import SolicitudesPaginacion from '@/components/SolicitudesServicios/viajarAhora/SolicitudesPaginacion';

// Generated by https://quicktype.io

export interface ListaSolicitudesServicioResponse {
  paginationInfo: {
    totalPages: number;
    totalElements: number;
    currentPage: number;
    currentElements: number;
  };
  elements: SolicitudServicioInfo[];
}

const ViajarAhoraPage = () => {
  let [userId] = useState<string>('e9c596b2-780b-4aea-845f-855d2678a8cd');
  let [apiService] = useState(new ApiService());
  const [paginacion, setPaginacion] = useState({
    page: 0,
    size: 10,
  });

  const [solicitudesServicio, setSolicitudesServicio] =
    useState<ListaSolicitudesServicioResponse>({
      paginationInfo: {
        totalPages: 0,
        totalElements: 0,
        currentPage: 0,
        currentElements: 0,
      },
      elements: [],
    });

  const { paginationInfo, elements } = solicitudesServicio;

  useEffect(() => {
    apiService
      .get<ListaSolicitudesServicioResponse>(
        '/solicitudes-servicios',
        paginacion
      )
      .then((data) => {
        setSolicitudesServicio(data);
      })
      .catch((err) => {
        return Swal.fire({
          icon: 'error',
          title: 'Oops...',
          text: 'No se pudo obtener las solicitudes',
        });
      });
  }, [paginacion]);

  const traerSiguientePagina = () => {
    setPaginacion((paginacion) => ({
      ...paginacion,
      page: paginacion.page + 1,
    }));
  };

  const traerAnteriorPagina = () => {
    setPaginacion((paginacion) => ({
      ...paginacion,
      page: paginacion.page - 1,
    }));
  };

  return (
    <Fragment>
      <div className='h-screen  flex flex-row justify-evenly flex-wrap'>
        <div className='h-screen' style={{ minWidth: '500px' }}>
          <CrearSolicitudServicio
            setSolicitudesServicio={setSolicitudesServicio}
          />
        </div>

        <div
          className='ml-5 overflow-y-auto h-screen w-max flex-grow'
          style={{ minWidth: '500px' }}
        >
          <SolicitudesServicioList
            solicitudesServicio={solicitudesServicio}
            setSolicitudesServicio={setSolicitudesServicio}
          />
          {paginationInfo.totalElements > 0 && (
            <SolicitudesPaginacion
              paginationInfo={paginationInfo}
              traerSiguientePagina={traerSiguientePagina}
              traerAnteriorPagina={traerAnteriorPagina}
            />
          )}
        </div>
      </div>
    </Fragment>
  );
};

export default ViajarAhoraPage;
