# ----------------------------------------------------------------------------------------------------------------------
# APPLICATION
spring:
  application:
    name: api-servicio-transporte
  profiles:
    active: pdn
  devtools:
    livereload:
      enabled: false
# ----------------------------------------------------------------------------------------------------------------------
# SERVER
server:
  port: 8080
# ----------------------------------------------------------------------------------------------------------------------